apiVersion: v2
name: model-evaluation
description: OpenShift AI Model Evaluation QuickStart
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - model-evaluation
  - openshift-ai
  - quickstart
home: https://github.com/rh-ai-quickstart/model-evaluation
sources:
  - https://github.com/rh-ai-quickstart/model-evaluation
maintainers:
  - name: Red Hat AI QuickStart Team

dependencies:
  - name: pgvector
    version: "0.5.1"
    repository: "https://rh-ai-quickstart.github.io/ai-architecture-charts"
    condition: pgvector.enabled

  - name: llm-service
    version: "0.5.2"
    repository: "https://rh-ai-quickstart.github.io/ai-architecture-charts"
    condition: llm-service.enabled
